.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo_05 - Debug ]----------"
	@cd "Ejemplo_05" && "$(MAKE)" -f  "Ejemplo_05.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo_05 - Debug ]----------"
	@cd "Ejemplo_05" && "$(MAKE)" -f  "Ejemplo_05.mk" clean
