.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo_03 - Debug ]----------"
	@cd "Ejemplo_03" && "$(MAKE)" -f  "Ejemplo_03.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo_03 - Debug ]----------"
	@cd "Ejemplo_03" && "$(MAKE)" -f  "Ejemplo_03.mk" clean
