.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo_06 - Debug ]----------"
	@cd "Ejemplo_06" && "$(MAKE)" -f  "Ejemplo_06.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo_06 - Debug ]----------"
	@cd "Ejemplo_06" && "$(MAKE)" -f  "Ejemplo_06.mk" clean
