.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo_02 - Debug ]----------"
	@cd "Ejemplo_02" && "$(MAKE)" -f  "Ejemplo_02.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo_02 - Debug ]----------"
	@cd "Ejemplo_02" && "$(MAKE)" -f  "Ejemplo_02.mk" clean
