.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo_08 - Debug ]----------"
	@cd "Ejemplo_08" && "$(MAKE)" -f  "Ejemplo_08.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo_08 - Debug ]----------"
	@cd "Ejemplo_08" && "$(MAKE)" -f  "Ejemplo_08.mk" clean
