.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo_07 - Debug ]----------"
	@cd "Ejemplo_07" && "$(MAKE)" -f  "Ejemplo_07.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo_07 - Debug ]----------"
	@cd "Ejemplo_07" && "$(MAKE)" -f  "Ejemplo_07.mk" clean
