.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo_01 - Debug ]----------"
	@cd "Ejemplo_01" && "$(MAKE)" -f  "Ejemplo_01.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo_01 - Debug ]----------"
	@cd "Ejemplo_01" && "$(MAKE)" -f  "Ejemplo_01.mk" clean
